### ISSUE TITLE
Register Bands in Town

### ISSUE THREAD

**Issue by msyatlaus** [nbur4556/dream-festival-lineup#4]

**Comment by rolara57** [comment]
sent email to bandsintown for api permission. cc'd Amy in email so more then 1 person can respond if needed.

**Comment by rolara57** [comment]
Hello Roger,

Thanks for your student request, you have permission to use our API for three months only: https://artists.bandsintown.com/support/public-api

By using the Bandsintown API you are signifying agreement with our general Terms of Use: http://corp.bandsintown.com/terms  and our API Terms of Use: http://corp.bandsintown.com/data-applications-terms

You will find your app ID on this Private note link. 

Have a Good day,

MAURICIO PRIETO

BANDSINTOWN GROUP

MONTREAL
//This is the email received by Bandsin town. key will follow

**Comment by rolara57** [comment]
9ebc2dc78f69f44da1e78195877b2314
bandsintown api key
